trigger:
 - master
pool:
 name: selfagent1

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'DACPAC'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Free Trial (a6d0e549-78fc-495b-a408-b3cdebadce37)'
    AuthenticationType: 'server'
    ServerName: 'sqldbserverone.database.windows.net'
    DatabaseName: 'database2'
    SqlUsername: 'sai'
    SqlPassword: 'Koushik10161016'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(System.DefaultWorkingDirectory)/_Project1-CI/drop/database1.dacpac'
    IpDetectionMethod: 'AutoDetect'