trigger:
 - master
pool:
 name: selfagent1

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  -  stage: Bulidcode
     displayName: Bulidcode

     jobs:
       -  job: 
          steps:
          - task: VSBuild@1
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: DEV
    pool: 
       name: selfagent1
    jobs: 
      -  job: webapp
         displayName: Dev-webapp
         steps:
           - task: DownloadBuildArtifacts@1
             inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: 'drop'
               downloadPath: '$(System.ArtifactsDirectory)'
           - task: AzureRmWebAppDeployment@4
             inputs:
               ConnectionType: 'AzureRM'
               azureSubscription: 'servicec1'
               appType: 'webApp'
               WebAppName: 'webappproejct2'
               packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
  - stage: UAT
    pool: 
       name: selfagent1
    jobs: 
      -  job: webapp
         displayName: UAT-webapp
         steps:
           - task: DownloadBuildArtifacts@1
             inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: 'drop'
               downloadPath: '$(System.ArtifactsDirectory)'
           - task: AzureRmWebAppDeployment@4
             inputs:
               ConnectionType: 'AzureRM'
               azureSubscription: 'servicec1'
               appType: 'webApp'
               WebAppName: 'webappproejct2'
               packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
  - stage: PROD
    pool:
     name: selfagent1
    jobs:
      -  deployment: prodwebapp
         environment: prod
         displayName: Prod-webapp
         strategy:
          runOnce:
             deploy:
                steps:
                  - task: DownloadBuildArtifacts@1
                    inputs:
                      buildType: 'current'
                      downloadType: 'single'
                      artifactName: 'drop'
                      downloadPath: '$(System.ArtifactsDirectory)'
                  - task: AzureRmWebAppDeployment@4
                    inputs:
                      ConnectionType: 'AzureRM'
                      azureSubscription: 'servicec1'
                      appType: 'webApp'
                      WebAppName: 'webappproejct2'
                      packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'